server:
  port: 9090

spring:
  application:
    name: policyMgmtUI
  mvc:
    view:
      suffix: .jsp
      prefix: /
  redis:
   host: localhost
   port: 6379
    
#eureka:
#  client:
#   registryFetchIntervalSeconds: 5
#    serviceUrl:
#        defaultZone: http://localhost:9190/eureka

  instance:
    prefer-ip-address: false  
    
